// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day4.Models;

[Table("Department")]
public partial class Department
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    public string name { get; set; }

    [StringLength(150)]
    public string Loc { get; set; }

    [InverseProperty("dept")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    [InverseProperty("Department")]
    public virtual ICollection<DepartmentCourse> DepartmentCourses { get; set; } = new List<DepartmentCourse>();
}